[
    {
        "name":"搜索引擎",
        "contain":[
            {
                "url":"http://www.baidu.com",
                "icon":"baidu",
                "name":"百度",
                "id":"1"
            },
            {
                "url":"http://www.so.com",
                "icon":"360",
                "name":"360",
                "id":"2"
            }
        ]
    },
    {
        "name":"门户网站",
        "contain":[
            {
                "url":"http://www.qq.com",
                "icon":"qq",
                "name":"腾讯",
                "id":"3"
            },
            {
                "url":"http://www.sohu.com",
                "icon":"souhu",
                "name":"搜狐",
                "id":"4"
            }
        ]
    },
    {
        "name":"社交网站",
        "contain":[
            {
                "url":"http://www.sina.com",
                "icon":"sina",
                "name":"新浪",
                "id":"5"
            }
        ]
    },
    {
        "name":"购物网站",
        "contain":[
            {
                "url":"http://www.jd.com",
                "name":"京东",
                "id":"6"
            },
            {
                "url":"http://www.taobao.com",
                "name":"淘宝",
                "id":"7"
            },
            {
                "url":"http://www.tmall.com",
                "name":"天猫",
                "id":"8"
            }
        ]
    },
    {
        "name":"首页",
        "contain":[
            {
                "url":"about:blank",
                "name":"空白",
                "id":"0"
            }
        ]
    }
]